- name: user directories
  file:
    path: "/mnt/storage/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ users }}"
- name: create link
  become_user: "{{ item }}"
  file:
    src: "/mnt/storage/{{ item.name }}"
    dest: "/home/{{ item.name }}/storage"
    state: link
  loop: "{{ users }}"
