- name: parted
  loop: "{{ storage.devices }}"
  parted:
    device: "{{ item }}"
    label: gpt
    number: 1
    state: present
- name: raid array
  include_role:
    name: ahharu.mdadm
  vars:
    mdadm_arrays:
      - name: md0
        devices: "{{ storage.devices | map('append', '1') | list }}"
        filesystem: ext4
        level: 6
        state: present
        mountpoint: /mnt/storage
