- name: create share directory
  become: true
  file:
    path: /mnt/storage/share
    state: directory
    owner: nobody
    group: sambashare
- name: samba share
  include_role:
    name: bertvv.samba
  vars:
    samba_map_to_guest: Bad User
    samba_server_min_protocol: SMB2
    samba_guest_account: nobody
    samba_shares:
      - name: MolCar
        path: /mnt/storage/share
        comment: Shared Storage
        group: sambashare
        browseable: true
        guest_ok: true
        guest_only: true
        writable: true
        public: true
- name: create link
  become: true
  become_user: "{{ item }}"
  file:
    src: /mnt/storage/share
    dest: "/home/{{ item }}/share"
    state: link
  with_items: "{{ commons_user.names }}"
