- name: install zsh
  apt:
    name: zsh
- name: install environments
  apt:
    name:
      - acl
- name: install build-tools
  apt:
    name:
      - build-essential
      - libssl-dev
      - libbz2-dev
      - zlib1g-dev
      - libreadline-dev
      - uuid-dev
      - libdb-dev
      - libsqlite3-dev
      - libffi-dev
