- name: remove default files
  loop:
    - $HOME/.bashrc
    - $HOME/.bash_logout
    - $HOME/.profile
  file:
    path: "{{ item }}"
    state: absent
- name: $ZDOTDIR
  file:
    path: $HOME/.config/zsh
    state: directory
