- hosts: localhost
  become: true
  roles:
    - commons
    - desktop
    - client
    - developer
  vars:
    users:
      - name: masaki
        anyenvs:
          - rbenv
          - nodenv
          - tfenv
          - pyenv
          - goenv
        prezto_plugins:
          - ruby
          - rails
          - python
