- hosts: laptop
  become: true
  roles:
    - commons
    - client
  vars:
    commons:
      users:
        - name: masaki
          anyenvs:
            - rbenv
            - nodenv
            - tfenv
            - pyenv
            - goenv
