- hosts: laptop
  become: true
  roles:
    - commons
    - client
  vars:
    users:
      - name: masaki
        anyenvs:
          - rbenv
          - nodenv
          - tfenv
          - pyenv
          - goenv
