---
- hosts: storage
  become: true
  roles:
    - commons
    - storage
  vars:
    commons:
      users:
        - name: masaki
    storage:
      devices:
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd
        - /dev/sde
        - /dev/sdf
        - /dev/sdg
