- name: install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto
    dest: $HOME/.zprezto
- name: find zsh files
  find:
    paths: $HOME/.zprezto/runcoms
    patterns: "z*"
  register: zsh_files
- name: copy zsh files
  loop: "{{ zsh_files.files }}"
  vars:
    src: "{{ item.path }}"
    dest: "$HOME/.{{ item.path.split('/') | last }}"
  copy:
    remote_src: yes
    src: "{{ src }}"
    dest: "{{ dest }}"
    force: no
