- get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google.asc
- apt_repository:
    repo: deb [arch=amd64, signed-by=/etc/apt/keyrings/google.asc] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
