- apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
- apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    filename: spotify
- apt:
    name: spotify-client
