- name: setup repos
  include_tasks: repos.yml
- name: setup packages
  include_tasks: packages.yml
- name: setup users
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  include_tasks: user.yml
