- name: install build-tools
  apt:
    name:
      - build-essential
      - rust-all
      - autoconf
      - automake
      - libssl-dev
      - libbz2-dev
      - zlib1g-dev
      - libreadline-dev
      - uuid-dev
      - libxml2-dev
      - libdb-dev
      - libsqlite3-dev
      - libmysql++-dev
      - libpq-dev
      - libffi-dev
- name: install apt packages
  apt:
    name:
      - jq
      - git
      - gh
      - ansible
- name: install snap packages
  community.general.snap:
    name:
      - peco
      - git-delta-snap
- name: install snap packages (--classic)
  community.general.snap:
    name: "{{ item }}"
    classic: true
  loop:
    - aws-cli
- name: alias snap
  community.general.snap_alias:
    name: git-delta-snap.delta
    alias: delta
