- block:
    - name: setup anyenv
      include_tasks: user/anyenv.yml
    - name: setup prezto
      include_tasks: user/prezto.yml
    - name: setup git
      include_tasks: user/git.yml
    #- name: setup gh
    #  include_tasks: user/gh.yml
  become_user: "{{ user.name }}"
  environment:
    ZDOTDIR: "/home/{{ user.name }}/.config/zsh"
    XDG_DATA_HOME: "/home/{{ user.name }}/.local/share"
    XDG_CONFIG_HOME: "/home/{{ user.name }}/.config"
