- include_tasks: user/zsh.yml
- block:
    - name: setup xdg-directories
      include_tasks: user/xdg-directories.yml
    - name: setup prezto
      include_tasks: user/prezto.yml
    - name: setup zprofile
      include_tasks: user/zprofile.yml
    - name: setup fcitx5
      include_tasks: user/setup-fcitx5.yml
  become_user: "{{ user.name }}"
  environment:
    ZDOTDIR: "/home/{{ user.name }}/.config/zsh"
    XDG_CONFIG_HOME: "/home/{{ user.name }}/.config"
    XDG_DATA_HOME: "/home/{{ user.name }}/.local/share"
    XDG_STATE_HOME: "/home/{{ user.name }}/.local/state"
    XDG_CACHE_HOME: "/home/{{ user.name }}/.cache"
