- name: install anyenv
  git:
    repo: https://github.com/anyenv/anyenv
    dest: "$HOME/.anyenv"
- name: create plugins
  file:
    path: "$HOME/.anyenv/plugins"
    state: directory
- name: install anyenv-update
  git:
    repo: https://github.com/znz/anyenv-update
    dest: "$HOME/.anyenv/plugins/anyenv-update"
- name: setup PATH
  lineinfile:
    path: "$HOME/.zshenv"
    line: "export PATH=$HOME/.anyenv/bin:$PATH"
- name: anyenv init
  lineinfile:
    path: "$HOME/.zshrc"
    line: 'eval "$(anyenv init -)"'
- shell:
    cmd: yes | anyenv install --init
    executable: zsh
    creates: $HOME/.config/anyenv
- name: install env
  loop: "{{ user.anyenvs }}"
  loop_control:
    loop_var: env_name
  shell:
    cmd: "anyenv install {{ env_name }}"
    executable: zsh
    creates: "$HOME/.anyenv/envs/{{ env_name }}"
