- name: install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto
    dest: $ZDOTDIR/.zprezto
- name: copy zsh files
  loop:
    - zpreztorc
    - zshenv
    - zshrc
    - zlogin
    - zlogout
  copy:
    remote_src: yes
    src: "$ZDOTDIR/.zprezto/runcoms/{{ item }}"
    dest: "$ZDOTDIR/.{{ item }}"
    force: no
- name: enable plugins
  lineinfile:
    path: $ZDOTDIR/.zpreztorc
    line: "  '{{ item }}' \\"
    insertbefore: "'prompt'"
  loop:
    - command-not-found
    - git
    - tmux
- name: copy .zprompt
  copy:
    src: zprompt.zsh
    dest: $ZDOTDIR/.zprompt
- name: load .zprompt
  lineinfile:
    path: $ZDOTDIR/.zshrc
    line: source "${ZDOTDIR:-$HOME}/.zprompt"
