- name: install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto
    dest: $HOME/.zprezto
- name: copy zsh files
  loop:
    - zpreztorc
    - zshenv
    - zshrc
    - zlogin
    - zlogout
  copy:
    remote_src: yes
    src: "$HOME/.zprezto/runcoms/{{ item }}"
    dest: "$HOME/.{{ item }}"
    force: no
- name: enable plugins
  lineinfile:
    path: $HOME/.zpreztorc
    line: "  '{{ item }}' \\"
    insertbefore: "'prompt'"
  loop:
    - command-not-found
    - git
    - tmux
