- name: import docker apt key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
- name: register docker apt repository
  apt_repository:
    repo: "deb [arch=amd64, signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
- name: assign users to docker group
  loop: "{{ users }}"
  user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
